# Generated by Django 5.2.2 on 2025-06-09 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_dangerous', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspected_at', models.DateTimeField(auto_now_add=True)),
                ('is_dangerous', models.BooleanField()),
                ('description', models.TextField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='safesurfing.url')),
            ],
        ),
    ]
